/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AlterarSenhaRouteImport } from './routes/alterar-senha'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RecuperarSenhaRouteImport } from './routes/recuperar-senha'
import { Route as RedefinirSenhaRouteImport } from './routes/redefinir-senha'
import { Route as AppHistoricoRouteImport } from './routes/_app.historico'
import { Route as AppPacientesRouteImport } from './routes/_app.pacientes'
import { Route as AppProfissionaisRouteImport } from './routes/_app.profissionais'
import { Route as ApiCompletePasswordChangeRouteImport } from './routes/api/complete-password-change'
import { Route as AppFilaIndexRouteImport } from './routes/_app.fila.index'
import { Route as AppFilaNovoRouteImport } from './routes/_app.fila.novo'
import { Route as ApiAdminUsersRouteImport } from './routes/api/admin/users'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AlterarSenhaRoute = AlterarSenhaRouteImport.update({
  id: '/alterar-senha',
  path: '/alterar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarSenhaRoute = RecuperarSenhaRouteImport.update({
  id: '/recuperar-senha',
  path: '/recuperar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const RedefinirSenhaRoute = RedefinirSenhaRouteImport.update({
  id: '/redefinir-senha',
  path: '/redefinir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const AppHistoricoRoute = AppHistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => AppRoute,
} as any)
const AppPacientesRoute = AppPacientesRouteImport.update({
  id: '/pacientes',
  path: '/pacientes',
  getParentRoute: () => AppRoute,
} as any)
const AppProfissionaisRoute = AppProfissionaisRouteImport.update({
  id: '/profissionais',
  path: '/profissionais',
  getParentRoute: () => AppRoute,
} as any)
const ApiCompletePasswordChangeRoute =
  ApiCompletePasswordChangeRouteImport.update({
    id: '/api/complete-password-change',
    path: '/api/complete-password-change',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppFilaIndexRoute = AppFilaIndexRouteImport.update({
  id: '/fila/',
  path: '/fila/',
  getParentRoute: () => AppRoute,
} as any)
const AppFilaNovoRoute = AppFilaNovoRouteImport.update({
  id: '/fila/novo',
  path: '/fila/novo',
  getParentRoute: () => AppRoute,
} as any)
const ApiAdminUsersRoute = ApiAdminUsersRouteImport.update({
  id: '/api/admin/users',
  path: '/api/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alterar-senha': typeof AlterarSenhaRoute
  '/login': typeof LoginRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/historico': typeof AppHistoricoRoute
  '/pacientes': typeof AppPacientesRoute
  '/profissionais': typeof AppProfissionaisRoute
  '/api/complete-password-change': typeof ApiCompletePasswordChangeRoute
  '/fila/novo': typeof AppFilaNovoRoute
  '/api/admin/users': typeof ApiAdminUsersRoute
  '/fila/': typeof AppFilaIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alterar-senha': typeof AlterarSenhaRoute
  '/login': typeof LoginRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/historico': typeof AppHistoricoRoute
  '/pacientes': typeof AppPacientesRoute
  '/profissionais': typeof AppProfissionaisRoute
  '/api/complete-password-change': typeof ApiCompletePasswordChangeRoute
  '/fila/novo': typeof AppFilaNovoRoute
  '/api/admin/users': typeof ApiAdminUsersRoute
  '/fila': typeof AppFilaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/alterar-senha': typeof AlterarSenhaRoute
  '/login': typeof LoginRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/_app/historico': typeof AppHistoricoRoute
  '/_app/pacientes': typeof AppPacientesRoute
  '/_app/profissionais': typeof AppProfissionaisRoute
  '/api/complete-password-change': typeof ApiCompletePasswordChangeRoute
  '/_app/fila/novo': typeof AppFilaNovoRoute
  '/api/admin/users': typeof ApiAdminUsersRoute
  '/_app/fila/': typeof AppFilaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alterar-senha'
    | '/login'
    | '/recuperar-senha'
    | '/redefinir-senha'
    | '/historico'
    | '/pacientes'
    | '/profissionais'
    | '/api/complete-password-change'
    | '/fila/novo'
    | '/api/admin/users'
    | '/fila/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alterar-senha'
    | '/login'
    | '/recuperar-senha'
    | '/redefinir-senha'
    | '/historico'
    | '/pacientes'
    | '/profissionais'
    | '/api/complete-password-change'
    | '/fila/novo'
    | '/api/admin/users'
    | '/fila'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/alterar-senha'
    | '/login'
    | '/recuperar-senha'
    | '/redefinir-senha'
    | '/_app/historico'
    | '/_app/pacientes'
    | '/_app/profissionais'
    | '/api/complete-password-change'
    | '/_app/fila/novo'
    | '/api/admin/users'
    | '/_app/fila/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AlterarSenhaRoute: typeof AlterarSenhaRoute
  LoginRoute: typeof LoginRoute
  RecuperarSenhaRoute: typeof RecuperarSenhaRoute
  RedefinirSenhaRoute: typeof RedefinirSenhaRoute
  ApiCompletePasswordChangeRoute: typeof ApiCompletePasswordChangeRoute
  ApiAdminUsersRoute: typeof ApiAdminUsersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alterar-senha': {
      id: '/alterar-senha'
      path: '/alterar-senha'
      fullPath: '/alterar-senha'
      preLoaderRoute: typeof AlterarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar-senha': {
      id: '/recuperar-senha'
      path: '/recuperar-senha'
      fullPath: '/recuperar-senha'
      preLoaderRoute: typeof RecuperarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redefinir-senha': {
      id: '/redefinir-senha'
      path: '/redefinir-senha'
      fullPath: '/redefinir-senha'
      preLoaderRoute: typeof RedefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/historico': {
      id: '/_app/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof AppHistoricoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pacientes': {
      id: '/_app/pacientes'
      path: '/pacientes'
      fullPath: '/pacientes'
      preLoaderRoute: typeof AppPacientesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profissionais': {
      id: '/_app/profissionais'
      path: '/profissionais'
      fullPath: '/profissionais'
      preLoaderRoute: typeof AppProfissionaisRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/complete-password-change': {
      id: '/api/complete-password-change'
      path: '/api/complete-password-change'
      fullPath: '/api/complete-password-change'
      preLoaderRoute: typeof ApiCompletePasswordChangeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/fila/': {
      id: '/_app/fila/'
      path: '/fila'
      fullPath: '/fila/'
      preLoaderRoute: typeof AppFilaIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/fila/novo': {
      id: '/_app/fila/novo'
      path: '/fila/novo'
      fullPath: '/fila/novo'
      preLoaderRoute: typeof AppFilaNovoRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/admin/users': {
      id: '/api/admin/users'
      path: '/api/admin/users'
      fullPath: '/api/admin/users'
      preLoaderRoute: typeof ApiAdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppHistoricoRoute: typeof AppHistoricoRoute
  AppPacientesRoute: typeof AppPacientesRoute
  AppProfissionaisRoute: typeof AppProfissionaisRoute
  AppFilaNovoRoute: typeof AppFilaNovoRoute
  AppFilaIndexRoute: typeof AppFilaIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppHistoricoRoute: AppHistoricoRoute,
  AppPacientesRoute: AppPacientesRoute,
  AppProfissionaisRoute: AppProfissionaisRoute,
  AppFilaNovoRoute: AppFilaNovoRoute,
  AppFilaIndexRoute: AppFilaIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AlterarSenhaRoute: AlterarSenhaRoute,
  LoginRoute: LoginRoute,
  RecuperarSenhaRoute: RecuperarSenhaRoute,
  RedefinirSenhaRoute: RedefinirSenhaRoute,
  ApiCompletePasswordChangeRoute: ApiCompletePasswordChangeRoute,
  ApiAdminUsersRoute: ApiAdminUsersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
