// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

/**
 * As novas publishable/secret keys do Supabase são strings opacas
 * e não JWTs.
 */
function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith("sb_publishable_") || value.startsWith("sb_secret_");
}

/**
 * Garante que a chave pública do Supabase seja enviada através
 * do header "apikey".
 *
 * Para as novas chaves opacas, removemos um Authorization
 * incorreto caso alguma camada tente utilizá-las como Bearer JWT.
 */
function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== "undefined" && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    if (
      isNewSupabaseApiKey(supabaseKey) &&
      headers.get("Authorization") === `Bearer ${supabaseKey}`
    ) {
      headers.delete("Authorization");
    }

    headers.set("apikey", supabaseKey);

    return fetch(input, {
      ...init,
      headers,
    });
  };
}

/**
 * Cria o cliente Supabase utilizado pela aplicação.
 *
 * Browser:
 *   import.meta.env.VITE_SUPABASE_*
 *
 * SSR / TanStack Start:
 *   process.env.VITE_SUPABASE_*
 *
 * As duas variáveis são públicas por natureza:
 * URL do projeto e publishable key.
 *
 * Não usamos SUPABASE_URL ou SUPABASE_PUBLISHABLE_KEY aqui,
 * pois o prefixo SUPABASE_ é reservado pelo Lovable Cloud para
 * variáveis internas gerenciadas pela própria plataforma.
 */
function createSupabaseClient() {
  const supabaseUrl = import.meta.env.VITE_SUPABASE_URL || process.env.VITE_SUPABASE_URL;

  const supabasePublishableKey =
    import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || process.env.VITE_SUPABASE_PUBLISHABLE_KEY;

  if (!supabaseUrl || !supabasePublishableKey) {
    const missing = [
      ...(!supabaseUrl ? ["VITE_SUPABASE_URL"] : []),
      ...(!supabasePublishableKey ? ["VITE_SUPABASE_PUBLISHABLE_KEY"] : []),
    ];

    const message = `Missing Supabase environment variable(s): ${missing.join(", ")}.`;

    console.error(`[Supabase] ${message}`);

    throw new Error(message);
  }

  return createClient<Database>(supabaseUrl, supabasePublishableKey, {
    global: {
      fetch: createSupabaseFetch(supabasePublishableKey),
    },

    auth: {
      storage: typeof window !== "undefined" ? localStorage : undefined,

      persistSession: true,
      autoRefreshToken: true,
    },
  });
}

/**
 * Criação lazy do cliente.
 *
 * Isso evita inicializar o Supabase antes que alguma parte da
 * aplicação realmente precise utilizá-lo.
 */
let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) {
      _supabase = createSupabaseClient();
    }

    return Reflect.get(_supabase, prop, receiver);
  },
});
